---

- name: Configuring port/protocol rules
  ufw: >
    port={{ item.port }}
    rule={{ item.rule if item.rule is defined else "allow" }}
    proto={{ item.proto if item.proto is defined else "any" }}
  with_items: ufw_rules
  tags:
    - networking
    - ufw
    - config

- name: Configuring network rules
  ufw: >
    from_ip="{{ item.ip }}"
    rule={{ item.rule if item.rule is defined else "allow" }}
  with_items: ufw_networks
  tags:
    - networking
    - ufw
    - config

- name: Configuring application rules
  ufw: >
    name="{{ item.name }}"
    rule={{ item.rule if item.rule is defined else "allow" }}
  with_items: ufw_applications
  tags:
    - networking
    - ufw
    - config

- name: Configuring firewall
  template: >
    src=etc-default-ufw.j2
    dest=/etc/default/ufw
    owner=root
    group=root
    mode=0644
  notify: reload ufw
  tags:
    - networking
    - ufw
    - config
