---

- name: Configuring port/protocol/network rules
  ufw: >
    port={{ item.port if item.port is defined else "" }}
    rule={{ item.rule if item.rule is defined else "allow" }}
    proto={{ item.proto if item.proto is defined else "any" }}
    to_ip="{{ item.to_ip if item.to_ip is defined else "any" }}"
    from_ip="{{ item.from_ip if item.from_ip is defined else "any" }}"
  with_items: ufw_rules
  tags:
    - networking
    - ufw
    - config

- name: Configuring application rules
  ufw: >
    name="{{ item.name }}"
    rule={{ item.rule if item.rule is defined else "allow" }}
  with_items: ufw_applications
  tags:
    - networking
    - ufw
    - config

- name: Configuring firewall
  template: >
    src=etc-default-ufw.j2
    dest=/etc/default/ufw
    owner=root
    group=root
    mode=0644
  notify: reload ufw
  tags:
    - networking
    - ufw
    - config
