---

- name: Compatibility check
  fail: msg="This role only works on Debian and Archlinux systems"
  when: ansible_os_family != "Debian" and ansible_os_family != "Archlinux"

- include: install.yml
  tags:
    - networking
    - ufw
    - ufw-install

- include: reset.yml
  tags:
    - networking
    - ufw
    - ufw-reset

- include: config.yml
  tags:
    - networking
    - ufw
    - ufw-config

- include: service.yml
  tags:
    - networking
    - ufw
    - ufw-service
